### ISSUE TITLE
vmq_diverstiy doesn't work after reached max_restart_intensity

### ISSUE THREAD

**Issue by chenxinlong** [vernemq/vernemq#1241]
# Environment

- VerneMQ Version: 1.7.1
- OS: CentOS 7
- Erlang/OTP version (if building from source): N/A
- VerneMQ configuration (vernemq.conf) : Auth using redis 
- Cluster size/standalone: Both cluster and standalone reproduced

### Expected behavior

This issue is the continuation of #1154 

A temporary high network latency caused a timeout when vmq_diversity calls redis server, during this period, vernemq couldn't accept any new connection. 

What I expected was after the network latency restores to normal, vernemq continues auth new connections and the vmq_diversty related processes works normally. 

### Actual behaviour

The actual behaviour is , after the network latency restores to normal after few minutes, vernemq still couldn't auth new connections and there's a lot of CRASH info within logs.

According to the console.log,  my guess is  :  After a few quick retries, some of the vmq_diversity related processes shut down for the reason of reached a `reached_max_restart_intensity`. 

Logs : 

* [console.log](https://github.com/vernemq/vernemq/files/3357501/console.log)
* [crash.log](https://github.com/vernemq/vernemq/files/3357502/crash.log)
* [error.log](https://github.com/vernemq/vernemq/files/3357503/error.log)
* [erlang.3.log](https://github.com/vernemq/vernemq/files/3357505/erlang.3.log)
* [erlang.4.log](https://github.com/vernemq/vernemq/files/3357506/erlang.4.log)

### Reproduce 

Steps : 

1. Fabricate a high latency network environment on eth0 (or loopback if the `vmq_diversity.redis.host` is  localhost) , a 5030ms delay is enough to triggers this problem.

    ```
    sudo tc qdisc add dev eth0 root netem delay 5030ms 10ms
    ```
2. Use any mqtt client connect to vernemq.
3. Connection establishes fail , wait few secs and the console.log outputs `xxx exit with reason reached_max_restart_intensity`. 
4. Restore the network environment to normal use : 
    ```
    sudo tc qdisc del dev eth0 root netem delay 5030ms 10ms
    ```
5. Use any mqtt client connect to vernemq, it fails.  
6. Restart the vernemq service, everything works well again.

**Comment by ioolkos** [comment]
@chenxinlong thanks... I think you analysis is fully correct. We'll see what we can do about the restart exhaustion.

**Comment by larshesel** [comment]
Hi @chenxinlong would you be able to test on current master? We've merged this which will be part of 1.8.1 or 1.9.0 not too long ago: https://github.com/vernemq/vernemq/pull/1186

**Comment by chenxinlong** [comment]
Hi, I've tried few times, but I can't build master successfully. The`make rel` outputs : 
```
cat vars.config > vars.generated
echo "{app_version, \"1.8.0-18-gbc153a4\"}." >> vars.generated
/usr/local/downloads/vernemq_master/rebar3  release
===> "/usr/local/downloads/vernemq_master/_build/default/lib/eleveldb/ebin/eleveldb.app" is missing description entry
===> "/usr/local/downloads/vernemq_master/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> "/usr/local/downloads/vernemq_master/_build/default/lib/eleveldb/ebin/eleveldb.app" is missing description entry
===> "/usr/local/downloads/vernemq_master/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> Verifying dependencies...
===> "/usr/local/downloads/vernemq_master/_build/default/lib/ssl_verify_fun/ebin/ssl_verify_fun.app" is missing description entry
===> "/usr/local/downloads/vernemq_master/_build/default/lib/riak_dt/ebin/riak_dt.app" is missing description entry
===> "/usr/local/downloads/vernemq_master/_build/default/lib/eleveldb/ebin/eleveldb.app" is missing description entry
===> Compiling idna
make: *** [rel] Killed
```


OS : CentOS 7,  
Erlang/OTP : 22

**Comment by larshesel** [comment]
From what I could google this might be because you're low on memory and the make process terminates because of this.

**Comment by chenxinlong** [comment]
Hi, I've built vernemq from master and I can still reproduct it.  For more details, you can  watch  this video . https://send.firefox.com/download/1d585581cd30012d/#y2yNSgTJ2qiJoXUnnwHnzQ

**Comment by larshesel** [comment]
Hi, thanks for the detailed video. It seems like the supervisor restart strategy might need to be tuned a bit. The database queries have a 5 second default timeout value and whenever one of those are exceeded (which they all will due to the network latency introduced) then they exit abnormally - the supervisor (I think this is the `vmq_diversity_sup` top level supervisor) then experiences too many restarts of the children and eventually shuts down - essentially giving up as restarting children hadn't solved the problem.

In a normal setting, do you often experience these kinds of slow networks?

**Comment by chenxinlong** [comment]
I deployed vernemq service on servers in difference regions which form a cluster. One of the nodes is a littble far away from the redis server. So it occasionally have network latency problems.

**Comment by larshesel** [comment]
Hi

I tried to fix this here #1257 - looking at the redis client it handles reconnects itself and as such the gen_server call into the client can block indefinitely.

Would you be able to test this out?

**Comment by chenxinlong** [comment]
Hi, since the #1257 is not merged into master yet,  so I built vernemq from : 
1. built from https://github.com/larshesel/vernemq/tree/diversity-redis-fixes 
2. built from master, but edit the related file by my self according to [#1257 file change](https://github.com/vernemq/vernemq/pull/1257/files)

Both of it built successfully but outputs the same errror after start vernemq like pic below : 

![20190718114859](https://user-images.githubusercontent.com/9261954/61428125-6c8bed00-a953-11e9-9a92-c083b029be17.jpg)

**Comment by larshesel** [comment]
It's saying that it can't reach the host - so perhaps your redis isn't running at the moment?

**Comment by chenxinlong** [comment]
Yes the redis server is running.  I have three _built on my server. When I switch to the first master which is not include the bugfix content and restart vernemq , it's normal. 

https://send.firefox.com/download/10101b8d8daf5274/#4VHKBRPdQSye1lueLuecjA

**Comment by larshesel** [comment]
ok - perhaps there's some issue with the redis client (it was upgraded to the latest version) - I'll have to look into it

**Comment by larshesel** [comment]
Hi, I'm not able to reproduce this. If redis is running and VerneMQ is able to connect to it no errors are reported in the log files. If redis isn't running I get 

```
2019-07-30 10:23:00.721 [info] <0.224.0>@vmq_cluster:init:141 cluster event handler 'vmq_cluster' registered
2019-07-30 10:23:01.406 [info] <0.412.0>@vmq_diversity_app:start:71 enable auth script for redis "./share/lua/auth/redis.lua"
2019-07-30 10:23:01.448 [error] <0.441.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.431.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.443.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.427.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.439.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.437.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.429.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.433.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.423.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
2019-07-30 10:23:01.449 [error] <0.435.0> eredis: Re-establishing connection to "localhost":6379 due to {connection_error,econnrefused}
```

We'll merge the fix and then you can test when 1.9.0 is out and reopen or file a new issue in case the issue reappears.

**Comment by larshesel** [comment]
Btw the error `ehostunreach` means that there is no route to the host - which usually points to some kind of network config error - especially since this is on localhost.

**Comment by chenxinlong** [comment]
Thanks ,  will 1.8.1 include it ? 

![image](https://user-images.githubusercontent.com/9261954/62113437-2fc2dd00-b2e7-11e9-979d-9f7e27ebd05f.png)

**Comment by larshesel** [comment]
We'll skip 1.8.1 and go directly to 1.9.0 - planned to be released tomorrow.
